name: Process Downloads and Deploy

on:
  workflow_dispatch:
    inputs:
      spotify_url:
        description: 'Spotify URL to download'
        required: true
  push:
    branches: [ main ]

jobs:
  download_and_process:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read  # Permite acceder a información de otras acciones
      packages: read  # Requerido para descargar paquetes
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Process Download
        if: github.event_name == 'workflow_dispatch'
        env:
          SPOTIFY_DL_TOKEN: ${{ secrets.SPOTIFY_DL_TOKEN }}
        run: |
          mkdir -p downloads
          spotdl ${{ github.event.inputs.spotify_url }} --output downloads

      - name: Upload Downloaded Files
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4  # Versión actualizada para evitar errores
        with:
          name: spotify-downloads
          path: downloads/
          retention-days: 1

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          exclude_assets: '**.yml,**/.git*'